package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.CommitStatusPublisher
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.commitStatusPublisher
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    features {
        val feature1 = find<CommitStatusPublisher> {
            commitStatusPublisher {
                vcsRootExtId = "411"
                publisher = github {
                    githubUrl = "https://api.github.com"
                    authType = password {
                        userName = "dtretyakov"
                        password = "credentialsJSON:2e7632cf-adba-44ae-9aa4-3f196bd2fef5"
                    }
                }
            }
        }
        feature1.apply {
            vcsRootExtId = "${DslContext.settingsRoot.id}"
            publisher = github {
                githubUrl = "https://api.github.com"
                authType = personalToken {
                    token = "credentialsJSON:1f157e28-9566-463a-a597-06d7bc6b8ed2"
                }
            }
            param("github_oauth_user", "missingdays")
            param("secure:github_password", "")
            param("github_username", "")
        }
    }
}
